# Generated by Django 5.0.6 on 2026-05-19 22:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionCalidadVida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=32, unique=True)),
                ('nombre', models.CharField(max_length=128)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Dimensión de Calidad de Vida',
                'verbose_name_plural': 'Dimensiones de Calidad de Vida',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ambito', models.CharField(choices=[('salud', 'Salud'), ('autonomia', 'Autonomía'), ('relaciones', 'Relaciones'), ('ocio', 'Ocio y tiempo libre'), ('formacion', 'Formación'), ('empleo', 'Empleo'), ('vivienda', 'Vivienda'), ('participacion', 'Participación social'), ('espiritualidad', 'Espiritualidad y valores'), ('otro', 'Otro')], max_length=16)),
                ('descripcion', models.TextField(help_text='En el lenguaje de la persona cuando aplique.')),
                ('indicador_logro', models.TextField(help_text='Cómo se mide el éxito.')),
                ('apoyos_necesarios', models.TextField(blank=True)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=8)),
                ('estado', models.CharField(choices=[('propuesto', 'Propuesto'), ('activo', 'En curso'), ('logrado', 'Logrado'), ('mantenimiento', 'En mantenimiento'), ('abandonado', 'Abandonado')], default='propuesto', max_length=16)),
                ('visible_en_panel', models.BooleanField(default=False, help_text='Si está visible en panel/corcho del centro (con consentimiento de la persona).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsable_seguimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='objetivos_plan_vida', to='personas.profesional')),
            ],
            options={
                'verbose_name': 'Objetivo del Plan de Vida',
                'verbose_name_plural': 'Objetivos del Plan de Vida',
                'ordering': ['ambito', '-prioridad'],
            },
        ),
        migrations.CreateModel(
            name='PlanDeApoyo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_realizacion', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planes_apoyo', to='personas.profesional')),
            ],
            options={
                'verbose_name': 'Plan de apoyo al proyecto de vida',
                'verbose_name_plural': 'Planes de apoyo al proyecto de vida',
            },
        ),
        migrations.CreateModel(
            name='EntradaPlanApoyo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo_objetivo', models.CharField(help_text='Texto del objetivo. Puede coincidir con `objetivo_vinculado.descripcion`.', max_length=255)),
                ('actividades', models.TextField(blank=True, help_text='Actividades para alcanzar el objetivo.')),
                ('apoyo_que', models.TextField(blank=True, verbose_name='QUÉ (Apoyo)')),
                ('apoyo_quien', models.TextField(blank=True, verbose_name='QUIÉN (Me apoya)')),
                ('apoyo_cuando', models.TextField(blank=True, verbose_name='CUÁNDO (Me apoyan)')),
                ('observaciones', models.TextField(blank=True)),
                ('seguimiento_cuantitativo', models.TextField(blank=True)),
                ('seguimiento_descriptivo', models.TextField(blank=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('dimensiones_cdv', models.ManyToManyField(blank=True, help_text='Dimensiones de Calidad de Vida (modelo Schalock).', related_name='entradas', to='pia.dimensioncalidadvida')),
                ('objetivo_vinculado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_plan_apoyo', to='pia.objetivo')),
                ('plan_apoyo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='pia.plandeapoyo')),
            ],
            options={
                'verbose_name': 'Entrada · Plan de apoyo',
                'verbose_name_plural': 'Entradas · Plan de apoyo',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PlanDeVida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anualidad', models.PositiveSmallIntegerField(help_text='Año de referencia (2025, 2026, 2027...).')),
                ('estado', models.CharField(choices=[('elaboracion', 'En elaboración'), ('vigente', 'Vigente'), ('revision', 'En revisión anual'), ('archivado', 'Archivado')], default='elaboracion', max_length=16)),
                ('fecha_elaboracion', models.DateField(blank=True, null=True)),
                ('fecha_revision', models.DateField(blank=True, help_text='Última revisión anual realizada.', null=True)),
                ('fecha_proxima_revision', models.DateField(blank=True, help_text='Próxima revisión anual prevista.', null=True)),
                ('fecha_prevista_realizacion', models.DateField(blank=True, help_text='Fecha planificada para realizar el Plan (distinto de la fecha real de elaboración).', null=True)),
                ('pv_realizado', models.BooleanField(default=False, help_text="¿El Plan de Vida está realizado? Equivalente a la columna 'PV realizado' del Excel actual.")),
                ('pv_revisado', models.BooleanField(default=False, help_text="¿El Plan de Vida ha sido revisado? Equivalente a la columna 'PV revisado'.")),
                ('estado_revision', models.CharField(choices=[('en_plazo', 'En plazo'), ('fuera_plazo', 'Fuera de plazo'), ('pendiente', 'Pendiente')], default='pendiente', help_text='Estado del cumplimiento de plazos de revisión anual.', max_length=24)),
                ('compartido_con_residencia_vivienda', models.BooleanField(default=False, help_text='Marca cuando el usuario tiene servicios en dos modalidades (p.ej. residencia + vivienda) y el PV se comparte entre ambas.')),
                ('firmado_persona_at', models.DateTimeField(blank=True, null=True)),
                ('firmado_apoyo_at', models.DateTimeField(blank=True, null=True)),
                ('visible_en_paneles', models.BooleanField(default=False, help_text='Voluntad de la persona usuaria: si autoriza compartir objetivos en paneles/corchos del centro.')),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gestor_caso', models.ForeignKey(blank=True, help_text='Coordina elaboración, seguimiento y revisión. Máx. 30 casos por gestor/a.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planes_vida_gestionados', to='personas.profesional', verbose_name='Gestor/a de caso')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_vida', to='personas.personaatendida')),
                ('persona_referencia', models.ForeignKey(blank=True, help_text='Genera vínculo significativo y aporta información cotidiana.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planes_vida_referencia', to='personas.profesional', verbose_name='Persona de referencia')),
            ],
            options={
                'verbose_name': 'Plan de Vida',
                'verbose_name_plural': 'Planes de Vida',
                'ordering': ['-anualidad'],
            },
        ),
        migrations.AddField(
            model_name='plandeapoyo',
            name='plan_vida',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_apoyo', to='pia.plandevida'),
        ),
        migrations.AddField(
            model_name='objetivo',
            name='plan_vida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='pia.plandevida'),
        ),
        migrations.CreateModel(
            name='HistoriaDeVida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_recogida', models.DateField(blank=True, null=True)),
                ('notas_generales', models.TextField(blank=True)),
                ('texto_narrativo_final', models.TextField(blank=True, help_text='Narrativa final de la historia de vida tras la conversación con la persona.', verbose_name='Historia de Vida (redacción final)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facilitador', models.ForeignKey(blank=True, help_text='Profesional que facilita la conversación (suele ser persona de referencia).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historias_facilitadas', to='personas.profesional')),
                ('plan_vida', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historia_vida', to='pia.plandevida')),
            ],
            options={
                'verbose_name': 'Historia de Vida',
                'verbose_name_plural': 'Historias de Vida',
            },
        ),
        migrations.CreateModel(
            name='DocumentoPlanDeVida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('historia_vida', 'Historia de Vida'), ('algo_sobre_mi', 'Algo sobre mí'), ('revision_objetivos', 'Revisión de objetivos'), ('plan_apoyo', 'Plan de apoyo al proyecto de vida'), ('proyecto_vida', 'Proyecto de vida')], max_length=24)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('elaboracion', 'En elaboración'), ('completado', 'Completado'), ('revisado', 'Revisado')], default='pendiente', max_length=16)),
                ('url_almacenamiento', models.URLField(blank=True, help_text='Enlace a Teams / OneDrive / espacio compartido autorizado.', max_length=1024)),
                ('publicado_en_repriss', models.BooleanField(default=False, help_text="Solo aplica a 'Proyecto de Vida' y 'Plan de apoyo'. Dirección lo cuelga en REPRISS.")),
                ('fecha_completado', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_vida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='pia.plandevida')),
            ],
            options={
                'verbose_name': 'Documento del Plan de Vida',
                'verbose_name_plural': 'Documentos del Plan de Vida',
                'ordering': ['plan_vida', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='CambioSignificativo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ambito', models.CharField(choices=[('salud', 'Salud'), ('empleo', 'Empleo'), ('centro_vivienda', 'Cambio de centro o vivienda'), ('rutinas', 'Rutinas'), ('relaciones', 'Relaciones'), ('participacion', 'Participación social'), ('otro', 'Otro')], max_length=24)),
                ('descripcion', models.TextField()),
                ('fecha_deteccion', models.DateField()),
                ('requiere_actualizacion_plan', models.BooleanField(default=True)),
                ('procesado', models.BooleanField(default=False, help_text='True cuando ya se ha actualizado el Plan de Vida con este cambio.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detectado_por', models.ForeignKey(blank=True, help_text='Suele ser la persona de referencia.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cambios_detectados', to='personas.profesional')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_significativos', to='personas.personaatendida')),
                ('plan_vida', models.ForeignKey(blank=True, help_text='Plan de Vida vigente al detectar el cambio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_significativos', to='pia.plandevida')),
            ],
            options={
                'verbose_name': 'Cambio significativo',
                'verbose_name_plural': 'Cambios significativos',
                'ordering': ['-fecha_deteccion'],
            },
        ),
        migrations.CreateModel(
            name='AlgoSobreMi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='algo_sobre_mi_actualizados', to='personas.profesional')),
                ('plan_vida', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='algo_sobre_mi', to='pia.plandevida')),
            ],
            options={
                'verbose_name': 'Algo sobre mí',
                'verbose_name_plural': 'Algo sobre mí',
            },
        ),
        migrations.CreateModel(
            name='ProyectoDeVida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('sueno_1', models.TextField(blank=True, verbose_name='Sueño 1')),
                ('sueno_2', models.TextField(blank=True, verbose_name='Sueño 2')),
                ('sueno_3', models.TextField(blank=True, verbose_name='Sueño 3')),
                ('valores', models.TextField(blank=True, verbose_name='Valores')),
                ('me_gusta_dia_a_dia', models.TextField(blank=True, verbose_name='Lo que me gusta de mi día a día')),
                ('no_me_gusta_dia_a_dia', models.TextField(blank=True, verbose_name='Lo que NO me gusta de mi día a día')),
                ('apoyos_naturales', models.TextField(blank=True, verbose_name='Apoyos naturales')),
                ('apoyos_profesionales', models.TextField(blank=True, verbose_name='Apoyos profesionales')),
                ('apoyos_comunitarios', models.TextField(blank=True, verbose_name='Apoyos comunitarios')),
                ('hitos_historia_vida', models.TextField(blank=True, help_text='Eventos importantes de la vida de la persona.', verbose_name='Hitos · Mi Historia de Vida')),
                ('publicado_en_repriss', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('elaborado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_vida', to='personas.profesional')),
                ('plan_vida', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_vida', to='pia.plandevida')),
            ],
            options={
                'verbose_name': 'Proyecto de Vida',
                'verbose_name_plural': 'Proyectos de Vida',
            },
        ),
        migrations.CreateModel(
            name='RespuestaHistoriaVida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pregunta_codigo', models.CharField(help_text='Código estable (HV01, HV02...).', max_length=16)),
                ('pregunta_texto', models.TextField()),
                ('respuesta_texto', models.TextField(blank=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='pia.historiadevida')),
            ],
            options={
                'verbose_name': 'Respuesta · Historia de Vida',
                'verbose_name_plural': 'Respuestas · Historia de Vida',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RevisionObjetivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anualidad', models.PositiveSmallIntegerField(help_text='Año al que corresponde la revisión (2025, 2026...).')),
                ('fecha_revision', models.DateField()),
                ('que_ha_logrado', models.TextField(blank=True, verbose_name='¿Qué ha logrado hasta la fecha?')),
                ('motivo_no_consecucion', models.TextField(blank=True, verbose_name='Si no lo ha conseguido, ¿cuál puede ser el motivo?')),
                ('propuesta_apoyos', models.TextField(blank=True, verbose_name='¿Cómo podemos ayudarle? Propuestas de apoyo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='pia.objetivo')),
                ('realizada_por', models.ForeignKey(blank=True, help_text='Profesional que realiza la revisión (gestor/a de caso o persona de referencia).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisiones_objetivos', to='personas.profesional')),
            ],
            options={
                'verbose_name': 'Revisión de objetivo',
                'verbose_name_plural': 'Revisiones de objetivos',
                'ordering': ['-anualidad', '-fecha_revision'],
            },
        ),
        migrations.CreateModel(
            name='SeccionAlgoSobreMi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(help_text='Identificador estable (movilidad, higiene...).', max_length=32)),
                ('titulo', models.CharField(max_length=128)),
                ('contenido', models.TextField(blank=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='pia.algosobremi')),
            ],
            options={
                'verbose_name': 'Sección · Algo sobre mí',
                'verbose_name_plural': 'Secciones · Algo sobre mí',
                'ordering': ['orden'],
            },
        ),
        migrations.AddIndex(
            model_name='plandevida',
            index=models.Index(fields=['estado', 'fecha_proxima_revision'], name='pia_plandev_estado_2d7c45_idx'),
        ),
        migrations.AddIndex(
            model_name='plandevida',
            index=models.Index(fields=['gestor_caso', 'estado'], name='pia_plandev_gestor__c9bded_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='plandevida',
            unique_together={('persona', 'anualidad')},
        ),
        migrations.AlterUniqueTogether(
            name='documentoplandevida',
            unique_together={('plan_vida', 'tipo')},
        ),
        migrations.AddIndex(
            model_name='cambiosignificativo',
            index=models.Index(fields=['persona', '-fecha_deteccion'], name='pia_cambios_persona_b06e7d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='respuestahistoriavida',
            unique_together={('historia', 'pregunta_codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='revisionobjetivo',
            unique_together={('objetivo', 'anualidad')},
        ),
        migrations.AlterUniqueTogether(
            name='seccionalgosobremi',
            unique_together={('documento', 'codigo')},
        ),
    ]
