[pytest]
DJANGO_SETTINGS_MODULE = agora.settings.dev
python_files = test_*.py
addopts = -ra --strict-markers --tb=short
markers =
    slow: tests lentos (omitir con -m "not slow")
testpaths = tests personas pia intervenciones agenda indicadores core equipo
