# Generated by Django 5.0.6 on 2026-05-19 22:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intervenciones', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('individual', 'Individual'), ('familiar', 'Familiar'), ('multipro', 'Multiprofesional'), ('externa', 'Externa (recurso externo)')], default='individual', max_length=16)),
                ('inicio', models.DateTimeField(db_index=True)),
                ('fin', models.DateTimeField()),
                ('ubicacion', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('propuesta', 'Propuesta'), ('confirmada', 'Confirmada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('no_asiste', 'No asiste')], default='propuesta', max_length=16)),
                ('notas', models.TextField(blank=True)),
                ('notificada_a_familia', models.BooleanField(default=False)),
                ('notificada_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intervencion_resultante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cita_origen', to='intervenciones.intervencion')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='personas.personaatendida')),
                ('profesionales', models.ManyToManyField(blank=True, related_name='citas', to='personas.profesional')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['inicio'],
                'indexes': [models.Index(fields=['inicio', 'fin'], name='agenda_cita_inicio_698d17_idx')],
            },
        ),
    ]
