# Generated by Django 5.0.6 on 2026-05-19 22:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
        ('pia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoIntervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=32, unique=True)),
                ('nombre', models.CharField(max_length=128)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(default='slate', help_text='Tailwind color name para distinción visual.', max_length=16)),
            ],
            options={
                'verbose_name': 'Tipo de intervención',
                'verbose_name_plural': 'Tipos de intervención',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instrumento', models.CharField(choices=[('bvd', 'Baremo de Valoración de Dependencia'), ('icap', 'Inventario para la Planificación (ICAP)'), ('sis', 'Supports Intensity Scale (SIS)'), ('barthel', 'Índice de Barthel'), ('tinetti', 'Escala de Tinetti'), ('mmse', 'Mini-Mental (MMSE)'), ('otro', 'Otro')], max_length=16)),
                ('fecha', models.DateField()),
                ('puntuacion', models.JSONField(default=dict, help_text='Estructura según instrumento (subescalas, niveles, etc.).')),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aplicado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valoraciones', to='personas.profesional')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='personas.personaatendida')),
            ],
            options={
                'verbose_name': 'Valoración',
                'verbose_name_plural': 'Valoraciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Intervencion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(db_index=True)),
                ('descripcion', models.TextField()),
                ('confidencialidad', models.CharField(choices=[('normal', 'Normal'), ('rest_clinica', 'Restringida clínica'), ('rest_juridica', 'Restringida jurídica')], default='normal', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('objetivo_vinculado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervenciones', to='pia.objetivo')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervenciones', to='personas.personaatendida')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intervenciones', to='personas.profesional')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intervenciones', to='intervenciones.tipointervencion')),
            ],
            options={
                'verbose_name': 'Intervención',
                'verbose_name_plural': 'Intervenciones',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['persona', '-fecha_hora'], name='intervencio_persona_3e3a1a_idx')],
            },
        ),
    ]
