# Generated by Django 5.0.6 on 2026-06-16 16:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervenciones', '0001_initial'),
        ('personas', '0002_alter_personaatendida_numero_seguridad_social_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracion',
            name='categoria',
            field=models.CharField(choices=[('adaptativa', 'Escalas adaptativas'), ('calidad_vida', 'Calidad de vida'), ('inteligencia', 'Inteligencia'), ('conducta', 'Conducta'), ('personalidad', 'Personalidad'), ('deterioro_cognitivo', 'Deterioro cognitivo'), ('screening_tm', 'Screening trastornos mentales'), ('dependencia', 'Dependencia / autonomía')], default='dependencia', help_text='Categorización clínica del instrumento (jun 2026).', max_length=24),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='conclusiones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('completada', 'Completada'), ('firmada', 'Firmada')], default='borrador', max_length=12),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='fecha_firma',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='firmada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valoraciones_firmadas', to='personas.profesional'),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='pdf_generado',
            field=models.FileField(blank=True, help_text='PDF A4 institucional ÁGORA generado tras la firma.', null=True, upload_to='valoraciones/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='respuestas',
            field=models.JSONField(blank=True, default=dict, help_text='Ítems del cuestionario completados. Schema según instrumento.'),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='instrumento',
            field=models.CharField(choices=[('icap', 'ICAP — Inventario para la planificación'), ('abs_rc2', 'ABS-RC:2 — Conducta adaptativa residencial'), ('san_martin', 'Escala San Martín'), ('fumat', 'Escala FUMAT'), ('inico_feaps', 'Escala INICO-FEAPS'), ('kbit', 'K-BIT'), ('raven', 'Matrices Progresivas de Raven'), ('wisc_4', 'WISC-4'), ('bbta', 'BBTA'), ('dsah_ii', 'DSAH II'), ('camdex_ds', 'Camdex DS'), ('mec', 'MEC — Mini-Examen Cognoscitivo'), ('test_barcelona', 'Test Barcelona'), ('bvd', 'Baremo de Valoración de Dependencia (BVD)'), ('sis', 'Supports Intensity Scale (SIS)'), ('barthel', 'Índice de Barthel'), ('tinetti', 'Escala de Tinetti'), ('mmse', 'Mini-Mental (MMSE)'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='puntuacion',
            field=models.JSONField(blank=True, default=dict, help_text='Puntuaciones brutas, percentiles, niveles. Schema según instrumento.'),
        ),
        migrations.CreateModel(
            name='InformePsicologico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('inicial', 'Inicial'), ('evolutivo', 'Evolutivo')], max_length=12)),
                ('fecha', models.DateField()),
                ('contenido', models.JSONField(blank=True, default=dict, help_text='Secciones del informe. Schema según tipo (inicial / evolutivo).')),
                ('numero_colegiado', models.CharField(blank=True, max_length=32)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('completado', 'Completado'), ('firmado', 'Firmado')], default='borrador', max_length=12)),
                ('fecha_firma', models.DateField(blank=True, null=True)),
                ('pdf_generado', models.FileField(blank=True, null=True, upload_to='informes_psicologicos/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_psicologicos', to='personas.personaatendida')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informes_psicologicos', to='personas.profesional')),
            ],
            options={
                'verbose_name': 'Informe psicológico',
                'verbose_name_plural': 'Informes psicológicos',
                'ordering': ['-fecha'],
            },
        ),
    ]
