# Generated by Django 5.0.6 on 2026-05-25 18:55

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaatendida',
            name='numero_seguridad_social',
            field=core.fields.EncryptedCharField(blank=True, help_text='NUSS. Categoría especial RGPD — cifrado en BD con Fernet (AES-128).', max_length=20, verbose_name='Nº Seguridad Social (NUSS)'),
        ),
        migrations.AlterField(
            model_name='personaatendida',
            name='numero_tarjeta_sanitaria',
            field=core.fields.EncryptedCharField(blank=True, help_text='TSI. Categoría especial RGPD — cifrado en BD con Fernet.', max_length=20, verbose_name='Nº Tarjeta Sanitaria (TSI)'),
        ),
    ]
