# Generated by Django 5.0.6 on 2026-05-19 22:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=32, unique=True)),
                ('nombre', models.CharField(max_length=128)),
                ('descripcion', models.TextField(blank=True)),
                ('unidad', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('ratio', 'Ratio'), ('absoluto', 'Absoluto')], default='absoluto', max_length=16)),
                ('objetivo_valor', models.DecimalField(blank=True, decimal_places=2, help_text='Valor diana del indicador (ej. ocupación ≥ 92%).', max_digits=10, null=True)),
                ('requiere_anonimizacion', models.BooleanField(default=True, help_text='Si True, el exporte externo se hace pseudonimizado.')),
                ('formula', models.CharField(blank=True, help_text="Referencia a la función de cálculo (ej. 'agora.indicadores.calc.ocupacion').", max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='SnapshotPlanesVida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(help_text='Fecha del snapshot.', unique=True)),
                ('etiqueta', models.CharField(blank=True, help_text="Etiqueta libre (p.ej. 'cierre trimestre 2026Q2').", max_length=128)),
                ('total_usuarios', models.PositiveIntegerField(default=0)),
                ('usuarios_fab', models.PositiveIntegerField(default=0)),
                ('usuarios_aspaniasmerc', models.PositiveIntegerField(default=0)),
                ('pv_realizados', models.PositiveIntegerField(default=0)),
                ('pv_pendientes', models.PositiveIntegerField(default=0)),
                ('pv_revisados', models.PositiveIntegerField(default=0)),
                ('pv_fuera_plazo', models.PositiveIntegerField(default=0)),
                ('desglose_centros', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots_pv', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Snapshot Planes de Vida',
                'verbose_name_plural': 'Snapshots Planes de Vida',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MedicionIndicador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periodo', models.DateField(help_text='Primer día del periodo medido (mensual/trimestral).')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('calculado_at', models.DateTimeField(auto_now_add=True)),
                ('centro', models.ForeignKey(blank=True, help_text='Null = global del grupo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mediciones', to='personas.centro')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='indicadores.indicador')),
            ],
            options={
                'verbose_name': 'Medición de indicador',
                'verbose_name_plural': 'Mediciones de indicadores',
                'ordering': ['-periodo', 'indicador'],
                'indexes': [models.Index(fields=['indicador', '-periodo'], name='indicadores_indicad_1b7f2b_idx')],
                'unique_together': {('indicador', 'periodo', 'centro')},
            },
        ),
    ]
