# deshacer_reorganizacion.ps1
# Revierte los movimientos de reorganizar_repo.ps1
# Generado: 2026-06-15 19:01:05

$ErrorActionPreference = 'Continue'
Write-Host 'Revirtiendo reorganizacion...' -ForegroundColor Yellow

Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\utilidades\pseudonimizar_excel_pv.py' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\pseudonimizar_excel_pv.py' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\utilidades\prueba_seco_importador.py' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\prueba_seco_importador.py' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\utilidades\limpiar_comentarios_django.py' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\limpiar_comentarios_django.py' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\utilidades\lanzar_claude.bat' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\lanzar_claude.bat' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\utilidades\generar_mapa_interactivo.py' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\generar_mapa_interactivo.py' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\utilidades\auditar_demo.py' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\auditar_demo.py' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\utilidades\arranque_local.md' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\arranque_local.md' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\utilidades\analizar_cgpr_estructura.py' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\analizar_cgpr_estructura.py' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\historico\reordenar_tabla_centro.py' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\reordenar_tabla_centro.py' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\historico\rellenar_tabs_persona.py' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\rellenar_tabs_persona.py' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\historico\reinsertar_tabs_familia_medico.py' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\reinsertar_tabs_familia_medico.py' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\historico\refactor_sidebar_v2.py' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\refactor_sidebar_v2.py' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\historico\refactor_nombres_centros.py' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\refactor_nombres_centros.py' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\historico\refactor_nav_demo.py' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\refactor_nav_demo.py' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\historico\refactor_centros_count.py' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\refactor_centros_count.py' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\historico\rebrand_sipas_to_agora.py' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\rebrand_sipas_to_agora.py' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\historico\fix_modales_scope.py' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\fix_modales_scope.py' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\historico\fix_equipo_tab.py' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\fix_equipo_tab.py' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\historico\fix_centros_casos_sueltos.py' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\fix_centros_casos_sueltos.py' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\historico\fix_breadcrumbs_duplicados.py' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\fix_breadcrumbs_duplicados.py' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\historico\fix_backslash_definitivo.py' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\fix_backslash_definitivo.py' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\historico\aplicar_shell_ux.py' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\aplicar_shell_ux.py' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\historico\add_generar_factura.py' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\scripts\add_generar_factura.py' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\modelo-datos\modelo_actual.md' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\modelo-datos\modelo_v0_12.md' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\modelo-datos\historico\modelo_v0_9.md' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\modelo-datos\modelo_v0_9.md' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\modelo-datos\historico\modelo_v0_8.md' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\modelo-datos\modelo_v0_8.md' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\modelo-datos\historico\modelo_v0_7.md' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\modelo-datos\modelo_v0_7.md' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\modelo-datos\historico\modelo_v0_6.md' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\modelo-datos\modelo_v0_6.md' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\modelo-datos\historico\modelo_v0_5.md' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\modelo-datos\modelo_v0_5.md' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\modelo-datos\historico\modelo_v0_4.md' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\modelo-datos\modelo_v0_4.md' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\modelo-datos\historico\modelo_v0_3.md' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\modelo-datos\modelo_v0_3.md' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\modelo-datos\historico\modelo_v0_2.md' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\modelo-datos\modelo_v0_2.md' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\modelo-datos\historico\modelo_v0_11.md' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\modelo-datos\modelo_v0_11.md' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\modelo-datos\historico\modelo_v0_10.md' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\modelo-datos\modelo_v0_10.md' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\modelo-datos\historico\modelo_v0_1.md' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\modelo-datos\modelo_v0_1.md' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\modelo-datos\decisiones\analisis_cgpr_estructura.md' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\modelo-datos\analisis_cgpr_estructura.md' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\modelo-datos\decisiones\05_modulo_equipo_solapamiento.md' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\modelo-datos\decision_modulo_equipo_solapamiento.md' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\modelo-datos\decisiones\04_servicios_multiples.md' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\modelo-datos\decision_servicios_multiples.md' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\modelo-datos\decisiones\03_fis_incidencias.md' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\modelo-datos\decision_fis_incidencias.md' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\modelo-datos\decisiones\02_facturacion_servicios_extras.md' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\modelo-datos\decision_facturacion_servicios_extras.md' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\modelo-datos\decisiones\01_dinero_bolsillo.md' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\modelo-datos\decision_dinero_bolsillo.md' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\fases\fase4' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\fase4' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\fases\fase3' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\fase3' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\fases\fase1' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\fase1' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\fases\fase0' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\docs\fase0' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\dist\historico\AGORA-demo-2026-05-19.zip' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\AGORA-demo-2026-05-19.zip' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\dist\actual\AGORA-demo-para-netlify.zip' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\AGORA-demo-para-netlify.zip' -Force
Move-Item -Path 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\_PARA_REVISAR\frontend_vacia' -Destination 'C:\Users\fmartinez\OneDrive - Aspanias\Escritorio\Documentos ESCRITORIO\04_PROYECTOS_Y_MEMORIAS\04_011_OTROS_PROYECTOS\PROYECTOS_TRABAJO\agora-aspanias\frontend' -Force

Write-Host 'Hecho.' -ForegroundColor Green
