# Generated by Django 5.0.6 on 2026-05-19 22:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('persona_consultada_id', models.UUIDField(blank=True, db_index=True, help_text='UUID de la persona si el acceso afecta a una ficha concreta.', null=True, verbose_name='Persona atendida consultada')),
                ('accion', models.CharField(choices=[('leer', 'Leer'), ('editar', 'Editar'), ('crear', 'Crear'), ('eliminar', 'Eliminar'), ('exportar', 'Exportar'), ('firmar', 'Firmar'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión')], db_index=True, max_length=16)),
                ('entidad', models.CharField(blank=True, help_text='Nombre del modelo o sección consultada.', max_length=128, verbose_name='Entidad afectada')),
                ('ruta', models.CharField(blank=True, max_length=512, verbose_name='Ruta')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('motivo', models.CharField(blank=True, help_text='Justificación del acceso cuando se requiera.', max_length=255, verbose_name='Motivo')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accesos', to=settings.AUTH_USER_MODEL, verbose_name='Profesional')),
            ],
            options={
                'verbose_name': 'Registro de acceso (bitácora)',
                'verbose_name_plural': 'Registros de acceso (bitácora)',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['profesional', '-timestamp'], name='core_regist_profesi_73b926_idx'), models.Index(fields=['persona_consultada_id', '-timestamp'], name='core_regist_persona_07a16b_idx')],
            },
        ),
    ]
