# Generated by Django 5.0.6 on 2026-06-15 19:56

import core.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0002_alter_personaatendida_numero_seguridad_social_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioLaboral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anio', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2024), django.core.validators.MaxValueValidator(2099)])),
                ('convenio', models.CharField(choices=[('vii_discapacidad', 'VII Convenio Discapacidad (1 752 h/año)'), ('vii_residencias_mayores', 'VII Estatal Residencias (1 770 h/año)')], max_length=32)),
                ('jornada_anual_horas', models.PositiveSmallIntegerField(help_text='Horas anuales convenio. 1 752 (DI) / 1 770 (Res Mayores).')),
                ('festivos', models.JSONField(default=list, help_text='Lista [{"fecha":"2026-01-01","tipo":"nacional","nombre":"Año Nuevo"}, ...]')),
                ('version', models.CharField(default='v1.0', max_length=8)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('aprobado_direccion', 'Aprobado por Dirección'), ('enviado_rlt', 'Enviado a RLT'), ('firmado', 'Firmado por RLT'), ('publicado', 'Publicado en tablón'), ('sustituido', 'Sustituido')], default='borrador', max_length=24)),
                ('fecha_aprobacion_direccion', models.DateField(blank=True, null=True)),
                ('fecha_firma_rlt', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendarios_aprobados', to=settings.AUTH_USER_MODEL)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calendarios_laborales', to='personas.centro')),
            ],
            options={
                'verbose_name': 'Calendario laboral del centro',
                'verbose_name_plural': 'Calendarios laborales del centro',
                'ordering': ['-anio', 'centro__nombre'],
            },
        ),
        migrations.CreateModel(
            name='CamposLaboralesProfesional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dni_cifrado', core.fields.EncryptedCharField(blank=True, max_length=64)),
                ('telefono_interno', models.CharField(blank=True, max_length=16)),
                ('tipo_jornada', models.CharField(choices=[('completa', 'Completa'), ('parcial', 'Parcial'), ('fin_de_semana', 'Fin de semana'), ('relevo', 'Relevo')], default='completa', max_length=16)),
                ('horario_habitual', models.CharField(choices=[('lv_manana', 'L-V mañana'), ('lv_tarde', 'L-V tarde'), ('rotativo', 'Rotativo M/T/N'), ('nocturno_fijo', 'Nocturno fijo'), ('veinticuatro', '24 horas (vivienda tutelada)'), ('anti_estres', 'Antiestrés CD')], default='lv_manana', max_length=16)),
                ('tipo_contrato', models.CharField(choices=[('indefinido', 'Indefinido'), ('temporal', 'Temporal'), ('obra_servicio', 'Obra y servicio'), ('bolsa', 'Bolsa de refuerzo'), ('formacion', 'Formación')], default='indefinido', max_length=20)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('fecha_baja_grupo', models.DateField(blank=True, help_text='Si no es null, el profesional ya no trabaja en el grupo.', null=True)),
                ('origen', models.CharField(choices=[('manual', 'Manual'), ('equipo', 'Sinc. EQUIPO'), ('sigper', 'Sinc. SIGPER')], default='manual', help_text='Origen del registro. En Fase 5 vendrá de EQUIPO vía API.', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centro_principal', models.ForeignKey(blank=True, help_text='Centro donde el profesional desarrolla la mayoría de su jornada.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profesionales_principal', to='personas.centro')),
                ('profesional', models.OneToOneField(help_text='Profesional al que pertenecen estos datos laborales.', on_delete=django.db.models.deletion.CASCADE, related_name='laboral', to='personas.profesional')),
            ],
            options={
                'verbose_name': 'Datos laborales del profesional',
                'verbose_name_plural': 'Datos laborales de profesionales',
            },
        ),
        migrations.CreateModel(
            name='PatronTurno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=64, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('ciclo_dias', models.PositiveSmallIntegerField(help_text='Duración del ciclo en días. 7 = semanal, 14 = quincenal.')),
                ('secuencia', models.JSONField(help_text='Lista de códigos de turno por día. Ej: ["M","M","T","T","N","N","D"].')),
                ('horas_por_turno', models.JSONField(default=dict, help_text='Horas que aporta cada código. Ej: {"M":8,"T":7,"N":10,"D":0}.')),
                ('horas_semana', models.PositiveSmallIntegerField(help_text='Horas semanales teóricas del patrón (40, 35, 24, etc.).')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centros', models.ManyToManyField(blank=True, help_text='Centros donde aplica este patrón. Vacío = todos.', to='personas.centro')),
            ],
            options={
                'verbose_name': 'Patrón de turno',
                'verbose_name_plural': 'Patrones de turno',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionPatron',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, help_text='Null = vigente.', null=True)),
                ('offset_inicio_ciclo', models.PositiveSmallIntegerField(default=0, help_text="Día del ciclo en que arranca el profesional el 'fecha_inicio'. Permite que dos profesionales con el mismo patrón estén desfasados.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_patron', to='personas.profesional')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='equipo.patronturno')),
            ],
            options={
                'verbose_name': 'Asignación de patrón',
                'verbose_name_plural': 'Asignaciones de patrón',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('franja', models.CharField(choices=[('manana', 'Mañana (07-15)'), ('tarde', 'Tarde (15-22)'), ('noche', 'Noche (22-07)'), ('partido', 'Partido'), ('veinticuatro', '24 horas')], max_length=16)),
                ('horas_efectivas', models.DecimalField(decimal_places=2, default=0, help_text='Suma de horas efectivas que cubre el turno.', max_digits=4)),
                ('notas', models.TextField(blank=True)),
                ('es_refuerzo', models.BooleanField(default=False, help_text='Marca si el turno es excepcional (cobertura de sustituciones, etc.).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='personas.centro')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_creados', to=settings.AUTH_USER_MODEL)),
                ('profesionales', models.ManyToManyField(blank=True, related_name='turnos', to='personas.profesional')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['fecha', 'franja'],
            },
        ),
        migrations.CreateModel(
            name='Vacacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('vacaciones', 'Vacaciones'), ('asuntos_propios', 'Asuntos propios'), ('formacion', 'Formación'), ('permiso_retribuido', 'Permiso retribuido'), ('it', 'Incapacidad temporal (IT)'), ('it_prolongada', 'IT prolongada'), ('lactancia', 'Lactancia / maternidad'), ('otro', 'Otro')], max_length=24)),
                ('estado', models.CharField(choices=[('solicitada', 'Solicitada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('disfrutada', 'Disfrutada'), ('en_curso', 'En curso'), ('anulada', 'Anulada')], default='solicitada', max_length=16)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('motivo', models.TextField(blank=True, help_text='Opcional. Obligatorio si tipo=asuntos_propios/permiso_retribuido.')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('dias_naturales', models.PositiveSmallIntegerField(default=0)),
                ('dias_laborables', models.PositiveSmallIntegerField(default=0)),
                ('origen', models.CharField(choices=[('manual', 'Manual'), ('sigper', 'Sincronizada desde SIGPER')], default='manual', max_length=16)),
                ('referencia_sigper', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aprobada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacaciones_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacaciones', to='personas.profesional')),
            ],
            options={
                'verbose_name': 'Vacación / ausencia',
                'verbose_name_plural': 'Vacaciones y ausencias',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddConstraint(
            model_name='calendariolaboral',
            constraint=models.UniqueConstraint(fields=('centro', 'anio', 'version'), name='calendario_centro_anio_version_unico'),
        ),
        migrations.AddConstraint(
            model_name='asignacionpatron',
            constraint=models.CheckConstraint(check=models.Q(('fecha_fin__isnull', True), ('fecha_fin__gte', models.F('fecha_inicio')), _connector='OR'), name='asignacion_patron_fecha_valida'),
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(fields=('centro', 'fecha', 'franja'), name='turno_centro_fecha_franja_unico'),
        ),
        migrations.AddConstraint(
            model_name='vacacion',
            constraint=models.CheckConstraint(check=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='vacacion_fecha_valida'),
        ),
    ]
